# Basic
title: Fynil
subtitle: 又不是不能用🐶
welcome_message: <a href="https://github.com/fynil" target="_blank">Fynil</a>
description: 懒癌晚期的夜猫子，写不出好程序的码农，唱不上高音，学不会吉他指弹的音乐爱好者 ，暂时在开发 iOS，💊
creator: <a href="http://fynil.cn">@Fynil</a>

url: "https://github.com/Fynil"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: My Projects, url: 'http://github.com/fynil'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: westplace
    github: Fynil
    mail: fynil@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
